missing definition of max
Maybe it is std::max?

We could use std::max, but i think that would be technically illegal c++ because std::max is not guaranteed to be a compile-time-constant-expression even if *all* of its arguments are, then you are into the "C variable length array extension" territory which is also not strictly legal c++, but we can work around that by using a simple macro

Patcher.cpp: In member function 'void Patcher::PatchContext::Init()':
Patcher.cpp:331:19: error: 'max' was not declared in this scope; did you mean 'std::max'?
  331 |         uint8 buf[max(sizeof(IMAGE_NT_HEADERS), sizeof(IMAGE_NT_HEADERS64))];
      |                   ^~~
      |                   std::max